### ISSUE TITLE
品类数量结构占比

### ISSUE THREAD

**Issue by Nancyccai** [Devin-Yeung/herbivorous-code#2]
品类数量结构占比，某品类销售量/总销售量*100%
![image](https://github.com/Devin-Yeung/herbivorous-code/assets/144206439/e2390541-f09e-4005-8cf2-2e3e058a7a1f)

**Comment by Devin-Yeung** [comment]
> 可以吗？可以这种简单的看品类分步嘛?把相同品类的销量进行加和

解决第几问？

**Comment by Nancyccai** [comment]
1的不同品类之间的销量的分布情况
