### ISSUE TITLE
1.2 解决方法

### ISSUE THREAD

**Issue by KIMAMao** [Devin-Yeung/herbivorous-code#3]
大致思路：
1. 先用描述性统计判断各个类别的分布是正态还是偏态
   具体步骤：计算该类别变量的均值和标准差。正态分布的数据通常具有零偏度(skewness)和零峰度 (kurtosis) 。均值接近零，标准差接近1。但这并不是绝对规则。偏度和峰度可用于量化数据的偏斜和尖峰性。如果偏度和峰度都接近零，那么该类别变量可能服从正态分布

2. 判断是否满足方差齐性

3. 若正态且满足方差齐性用单因素方差分析，反之用K开头的那个

5. 单因素方差分析前提：数据满足正态性和方差齐性
  Kruskal-Wallis 检验 适用于偏态数据和不满足方差齐性时

单因素方差分析 [reference：单因素方差分析](https://zhuanlan.zhihu.com/p/161956239#:~:text=%E5%85%B6%E5%9F%BA%E6%9C%AC%E6%80%9D%E6%83%B3%E6%98%AF%E5%B0%86%E5%85%A8%E9%83%A8%E8%A7%82%E5%AF%9F%E5%80%BC%E9%97%B4%E7%9A%84%E5%8F%98%E5%BC%82%E2%80%94%E2%80%94%E6%80%BB%E5%8F%98%E5%BC%82%E6%8C%89%E8%AE%BE%E8%AE%A1%E5%92%8C%E9%9C%80%E8%A6%81%E5%88%86%E8%A7%A3%E6%88%90%E4%B8%A4%E4%B8%AA%E6%88%96%E5%A4%9A%E4%B8%AA%E7%BB%84%E6%88%90%E9%83%A8%E5%88%86%EF%BC%8C%E5%86%8D%E4%BD%9C%E5%88%86%E6%9E%90%E3%80%82%20%E6%9C%AC%E6%96%87%E5%B0%86%E9%92%88%E5%AF%B9%E5%8D%95%E5%9B%A0%E7%B4%A0%E6%96%B9%E5%B7%AE%E5%88%86%E6%9E%90%20%28One-Way%20ANOVA%29%E5%BC%80%E5%B1%95R%E8%AF%AD%E8%A8%80%E7%9A%84%E5%AE%9E%E8%B7%B5%E3%80%82%20%E5%8D%95%E5%9B%A0%E7%B4%A0%E6%96%B9%E5%B7%AE%E5%88%86%E6%9E%90%E6%98%AF%E5%B0%86%E5%90%8C%E8%B4%A8%E7%9A%84%E5%8F%97%E8%AF%95%E5%AF%B9%E8%B1%A1%E9%9A%8F%E6%9C%BA%E5%9C%B0%E5%88%86%E9%85%8D%E5%88%B0%E5%90%84%E5%A4%84%E7%90%86%E7%BB%84%EF%BC%8C%E5%86%8D%E8%A7%82%E5%AF%9F%E5%AF%B9%E6%AF%94%E5%AE%9E%E9%AA%8C%E6%95%88%E5%BA%94%E7%9A%84%E6%96%B9%E6%B3%95%E3%80%82,%E5%9C%A8%E5%8D%95%E5%9B%A0%E7%B4%A0%E6%96%B9%E5%B7%AE%E5%88%86%E6%9E%90%E4%B8%AD%EF%BC%8C%E9%A6%96%E5%85%88%E5%B0%86%E6%80%BB%E5%8F%98%E5%BC%82%20%28SS_%E6%80%BB%29%E5%88%86%E8%A7%A3%E4%B8%BA%E7%BB%84%E9%97%B4%E5%8F%98%E5%BC%82%20%28SS_%E7%BB%84%E9%97%B4%29%E4%B9%9F%E5%8F%AB%E5%A4%84%E7%90%86%E5%8F%98%E5%BC%82%E5%92%8C%E7%BB%84%E5%86%85%E5%8F%98%E5%BC%82%20%28SS_%E7%BB%84%E5%86%85%29%E4%B9%9F%E5%8F%AB%E8%AF%AF%E5%B7%AE%E5%8F%98%E5%BC%82%EF%BC%8C%E7%84%B6%E5%90%8E%E6%AF%94%E8%BE%83%E4%B8%A4%E8%80%85%E7%9A%84%E5%B9%B3%E5%9D%87%E5%8F%98%E5%BC%82%20%28MS_%E7%BB%84%E9%97%B4%EF%BC%8CMS_%E7%BB%84%E5%86%85%29%EF%BC%8C%E6%AF%94%E8%BE%83%E6%97%B6%E9%87%87%E7%94%A8%E4%B8%A4%E8%80%85%E7%9A%84%E6%AF%94%E5%80%BCF%E5%80%BC%20%28MS_%E7%BB%84%E9%97%B4%2FMS_%E7%BB%84%E5%86%85%29)
如果差异具有统计学意义，用Tukey HSD（Tukey Honest Significant Differences)，来看两个两个自变量之间的相关性

Kruskal-Wallis 检验 [reference：单因素方差分析](https://zhuanlan.zhihu.com/p/412100887)
如果差异具有统计学意义，后面还可以用多重wilcoxon检验，来看两个两个自变量之间的相关性（与前一个不同，一定不能搞混）

**Comment by Devin-Yeung** [comment]
See #5 @KIMAMao @Nancyccai
